### ISSUE TITLE
Min probability improvements based on @xeqi's comments

### ISSUE THREAD

**Issue by eparchas** [eparchas/fp-learning#1]
This issue tracks the attempt to improve the min probability code based on [@xeqi's](https://www.reddit.com/user/xeqi/) comments made in this [post](https://www.reddit.com/r/functionalprogramming/comments/tlm6tc/comment/i2dfk19/?utm_source=share&utm_medium=web2x&context=3), while still staying in the discrete solution domain. There will be a different [ticket](4) for the continuous based solution proposed in the same post. Here is a summary of the proposed changes:

1. If `unfold` should be a class method, it seems like it should call a static method passing in the initial `TraversalState`. This clean up highlights the inconsistent usage of `adjacents` and `probability`. They are passed as part of the `TraversalState`, but are sometimes directly referred to by using the inital `TraversalState,` sometimes through `ss.*` to get the "current" `TraversalState`. They are never changed and could just be passed in as arguments to unfold. This could also allow them to be removed from `TraversalState`. Additionally there looks to be a [`typo misuse of visited vs ss.visited`](https://github.com/eparchas/fp-learning/blob/e4a5e150f4f801378945ad6630f84c6632689ad4/min-probability/src/main/java/org/ep/traverse/TraversalState.java#L81).

2. My eye is next drawn to the removal of already `visited` points. It is done by both [checking the current point](https://github.com/eparchas/fp-learning/blob/e4a5e150f4f801378945ad6630f84c6632689ad4/min-probability/src/main/java/org/ep/traverse/TraversalState.java#L81) and by [filtering future points](https://github.com/eparchas/fp-learning/blob/e4a5e150f4f801378945ad6630f84c6632689ad4/min-probability/src/main/java/org/ep/traverse/TraversalState.java#L91). The removal of future points seems to indicate that you want to keep the condition that the `PriorityQueue` only contains unvisited points. It looks like this is violated when the PriorityQueue gets two of the same point added because the same unvisited point is generated by `adjacents` during different unfold steps. Filtering the future points with some form of `PriorityQueue.contains` on the final `<Point,Priority>` pair should prevent this.

3. Next I am drawn to `probabilityIdx`. It is used to add new points to the `PriorityQueue`. However the priority for those points already exists in `adjacentsMap`. Nothing from the old `probabilityIdx` is needed. This could be removed entirely from `TraversalState`.

4. This makes `TraversalState` basically a `Pair<Set, PriorityQueue>`. To me, this feels significantly better as it represents a pair of visited and unvisited points. Then I'd cleanup `TraversalState.unfold` by using `Option.map` to handle the `if(dequeueOpt.isDefined) {..} return Option.none();`.

5. In another language and more general problem setup I would think about how `TraversalState` now makes a Semigroup/Monoid (preserve the `PriorityQueue` only contains unvisited condition!) and how a `<>`/`merge` from a `TraversalState` of only new points could work to replace most of the unfold's inner function, but I don't think it gains much in this specific example.

**Comment by eparchas** [comment]
Regarding point 3, the probabilityIdx is required in order to keep track of the minimum maximum probability of detection en route to any point, as the same point may be reachable (but not already visited) by multiple paths. The `adjacentsMap` is merged with the `probabilityIdx` using `BigDecimal::min` so that if we reach the same point through multiple paths the one with the lowest total probability of detection is recorded.

**Comment by eparchas** [comment]
Regarding point 2, the reason that visited points are filtered both by checking the current point and future adjacent points has to do with the avoidance of recursion or `continue` in the while loop. Conceptually, the initial `TraversalState` is unfolded into a stream of pairs of points and minimum probability of detection to that point. When a visited point is encountered, the correct way to deal with it would be to skip it and continue to the next point in the queue. In a `while` loop this can be easily done with `continue`. In this case, this could be possibly done with recursion, however I wanted to avoid that in a language like Java. The solution is to emit the same point again and rely on the caller to continue the stream unfolding. To reduce the number of those cases, I also filtered on `queue` offer.

**Comment by xeqi** [comment]
I used some implicit knowledge about how the weighted graph traversal will unfold and was terse when I was writing 2/3 above.  I will attempt to explain longer as we've moved to a medium that works better for it.


An important property of the traversal is: **the first generation of a point has a minimal probability**.

A rough proof goes along the lines of:

- Take a point `p1` from the head of the queue.
- Point `adjancentToP1` is created when visiting `p1`, and `currentProb(adjancentToP1) = max(currentProb(p1), probability(adjancentToP1))`.
- Therefore paths always increase or stay equal in `currentProb`.
- Later take point `p2` from the queue, and have `p2` also generate `adjancentToP1`.
- Since `p2` was visited later than `p1`,  the `PriorityQueue` guarantees that there exists some point `p3` on the path to `p2` such that `currentProb(p1) <= currentProb(p3)` (or else each point on the path `p3`->`p2` would have been taken before `p1`).
- Paths always increase or stay equal in `currentProb` means  `currentProb(p1) <= currentProb(p2)`.
- Thus `max(currentProb(p1), probability(adjancentToP1)) <= max(currentProb(p2), probability(adjancentToP1))`.
- Therefore a smallest `currentProb(adjancentToP)` will be found when `adjancentToP` is first generated.

Another way to think about it is that the priority queue is managing a search based on the `currentProb` of a path, and paths can only increase or stay equal in `currentProb`. If there are two paths to the same point `p` then when the queue is deciding which path to choose to extend, it will always choose the lower `currentProb` path.  Therefore the lower `currentProb` path "reaches" `p` first.

The second generation of a point doesn't matter, as searching would already be proceeding from the first generation, and the final result only needs a single lowest probability path. It would be nice to not add the second generation to the queue at all.  At first I had hoped that a combination of `nextVisited::contains` and a method in the queue's api would work.

However, a guarantee that the queue only receives the first generation of a point can be done by using a set of `knownPoints`.  A filter against a new generation of a point with `knownPoints::contains` can be used, much like is currently done with `nextVisited::contains`.  The guarantee would require `TraversalState::init` to add the initial point to it's known points as well. Then since there is a guarantee that only one generation of a point gets put into the queue, `visited` and its check can be removed as they will never trigger.  Since only first generations of points get put in queue, `probabilityIdx`  will never be queried for data about already generated points, and thus `probabilityIdx` could be removed.

**Comment by eparchas** [comment]
@xeqi thank you for the clarification and for helping out. Thinking at it again, I don't think that using max of probability so far is the correct way to find 
> the lowest probability of detection achievable given the number and location of the detectors

This was obviously an error on my part. The probability of detection along a path `A, B` assuming that the detection at each point is independent of the detection to other points would be, as in the case of a point with multiple detectors, is `P(A) + P(B) - P(A&B)`. ~~This means that the individual probability of each point should be added to the queue, and the `probabilityIdx` (or accumulator) should accumulate the probabilities for each point. This however raises the question of whether following the path of least probability will always give us the least total probability of detection, since the length of the path now also effectively affects the total probability of detection (?).~~

**Comment by eparchas** [comment]
I updated PR #2 to calculate the total path to that point and use that in the Priority queue.
